apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - clusterrole.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - deployment.yaml

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.14.2
