apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/external-dns
  - namespace.yaml

namespace: external-dns

patches:
  - path: deployment-patch.yaml

configMapGenerator:
  - name: external-dns-config
    literals:
      - DOMAIN_FILTER=k8s.production

secretGenerator:
  - name: external-dns-secrets
    literals:
      - GOOGLE_PROJECT=<production-project>
      - GOOGLE_SERVICE_ACCOUNT=<production-service-account>

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: "v0.14.2"
