apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: local
spec:
  template:
    spec:
      containers:
      - name: nginx
        envFrom:
        - configMapRef:
            name: nginx-config
