apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: mysql-config
    files:
      - cdc.cnf=cdc.cnf

secretGenerator:
  - name: mysql-secrets
    literals:
      - MYSQL_ROOT_PASSWORD=admin
