apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: mysql-config
    files:
      - cdc.cnf=conf.d/cdc.cnf
  - name: mysql-init-scripts
    files:
      - debezium_setup.sql=initdb.d/debezium_setup.sql
  - name: mysql-env
    literals:
      - mysql-database=sourcedb
      - mysql-user=sourcedb_user

secretGenerator:
  - name: mysql-secrets
    literals:
      - mysql-root-password=secret
      - mysql-password=secret
      - debezium-user-password=secret
