apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: mysql-config
    files:
      - cdc.cnf=conf.d/cdc.cnf
  - name: mysql-init-scripts
    files:
      - debezium_setup.sql=initdb.d/debezium_setup.sql
  - name: mysql-env
    literals:
      - mysql-database=sourcedb

secretGenerator:
  - name: mysql-secret
    literals:
      - mysql-root-password=secret
      - mysql-user=dbowner
      - mysql-password=secret
  - name: debezium-secret
    literals:
      - username=debezium
      - password=secret
