apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: kafka-ui-env
    literals:
      - KAFKA_CLUSTERS_0_NAME=integrationhub
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=integrationhub-kafka-bootstrap.kafka.svc.cluster.local:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=integrationhub-zookeeper-client.kafka.svc.cluster.local:2181
