apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mysql.k8s.local
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
