apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          args:
            - --source=service
            - --source=ingress
            - --domain-filter=$(DOMAIN_FILTER)
            - --provider=rfc2136
            - --rfc2136-host=$(RFC2136_HOST)
            - --rfc2136-port=$(RFC2136_PORT)
            - --rfc2136-zone=$(RFC2136_ZONE)
            - --rfc2136-tsig-secret=$(RFC2136_TSIG_SECRET)
            - --rfc2136-tsig-secret-alg=hmac-sha256
            - --rfc2136-tsig-keyname=externaldns-key
            - --rfc2136-tsig-axfr
            - --registry=txt
            - --txt-owner-id=external-dns
          envFrom:
            - configMapRef:
                name: external-dns-config
            - secretRef:
                name: external-dns-secrets
          resources:
            requests:
              cpu: "250m" # Minimum CPU request in milliCPU units
              memory: "512Mi" # Minimum memory request in Mebibytes
            limits:
              cpu: "500m" # Maximum CPU limit in milliCPU units
              memory: "1Gi" # Maximum memory limit in Mebibytes
