apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../../base/external-dns

namespace: external-dns

patches:
  - path: deployment-patch.yaml

secretGenerator:
  - name: external-dns-secrets
    literals:
      - DOMAIN_FILTER=k8s.local
      - RFC2136_HOST=172.31.0.51
      - RFC2136_PORT=53
      - RFC2136_ZONE=k8s.local
      - RFC2136_TSIG_SECRET=A0DlkzhsT32fy5rHnYmWLF8T90c52+g3Uh+ABYGgLGE=

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: "v0.14.2"
