apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/docker-registry

namespace: docker-registry

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
