apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: webconsole
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: api
      port: 9000
      protocol: TCP
      targetPort: 9000
  type: ClusterIP
