apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
        - name: mysql
          envFrom:
            - secretRef:
                name: mysql-secrets
          resources:
            requests:
              cpu: "250m" # Minimum CPU request in milliCPU units
              memory: "512Mi" # Minimum memory request in Mebibytes
            limits:
              cpu: "500m" # Maximum CPU limit in milliCPU units
              memory: "1Gi" # Maximum memory limit in Mebibytes
