apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mysql
  - namespace.yaml

namespace: mysql

secretGenerator:
  - literals:
      - MYSQL_ROOT_PASSWORD=root
    name: mysql-secrets

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml

images:
  - name: mysql
    newTag: "8.4.2"
