apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mysql

namespace: mysql

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml

images:
  - name: mysql:latest
    newTag: "8.0.39"
