apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/external-dns

namespace: external-dns

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.14.2

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: external-dns-config
    literals:
      - DOMAIN_FILTER=k8s.stage

secretGenerator:
  - name: external-dns-secrets
    literals:
      - GOOGLE_PROJECT=my-stage-project
      - GOOGLE_SERVICE_ACCOUNT=my-service-account
